version: '3'

networks:
  web:
    external:
      name: web
services:
  hydra:
    labels:
      - 'traefik.backend=hydra'
      - 'traefik.port=4444'
      - 'traefik.frontend.rule=Host:hydra.YOUR_DOMAIN.COM'
    networks:
      web:
  hydra-migrate:
    labels:
      - traefik.enable=false

  postgres:
    labels:
      - traefik.enable=false
