version: '3.4'

networks:
  web:
    external:
      name: web
services:
  api:
    labels:
      - 'traefik.backend=api'
      - 'traefik.port=3000'
      - 'traefik.frontend.rule=Host:api.example.com'
      # Uncomment to password protect the Reaction API
      # - 'traefik.frontend.auth.basic.removeHeader=true'
      # - 'traefik.frontend.auth.basic=YOUR_USER:YOUR_ENCRYPTED_PASSWORD'
    networks:
      web:
  mongo:
    labels:
      - traefik.enable=false

